- package.json
See issue [#7618](https://github.com/angular/angular/issues/7618)
> chore: update es6-shim to v.0.35.0 per A2 issue #7618

- index.html
- karma.conf.js
- package.json
- typings.json
- typings/typings.d.ts
> chore: migrate to core-js

- app/app.component.spec.ts
This test is nice, but since we don't have content for testing yet in the guides, the error is giving problem to people running ToH.
Fixes #119
> chore: remove test

- README.md
This should be enough until we update to TS2.
Fixes #130 
Fixes #131
> chore: add typings warning

- package.json
> chore: update in-mem-api version

- package.json
- systemjs.config.js
> chore: update packages

- e2e/app.e2e-spec.ts
> Change var to let in e2e

- .gitignore
- CHANGELOG.md
- app/app.component.spec.ts
- app/app.component.ts
- app/main.ts
- package.json
Also took a moment to tidy-out some things.
> chore: update to RC4

- README.md
> chore(travis): add badge to readme

- README.md
Fixes https://github.com/angular/quickstart/issues/176
> chore(docs): use correct comment syntax

- README.md
Same update as the angular.io one.
> chore: update node and npm recommendations

- index.html
> chore: add doctype

- karma.conf.js
In line 47 and 48 have space, and the other not.
> standardizing of spaces

- .travis.yml
- package.json
See https://github.com/angular/webdriver-manager/issues/121
> fix(e2e): fix travis webdriver issue

- systemjs.config.js
Blocked by https://github.com/angular/angular.io/pull/2781 and Angular 2.2.0.
> [WIP] Add @angular/upgrade/static to systemjs.config.js

- CHANGELOG.md
- package.json
> chore: update to 2.3.0

- karma.conf.js
Add leading slash to appAssets variable
closes #329
> chore: add slash to appAssets in karma.conf (#329)

- package.json
This fixes processes being left alive in gitbash.
/cc @foxandxss
> build(deps): update concurrently

- src/index.html
PR created following discussions here: https://github.com/angular/quickstart/pull/368#issuecomment-283023424
> Removed secondary base href=/ element

- CHANGELOG.md
- package.json
> build: update to Angular 4
