angular/quickstart

package.json
Hi this is just a suggestion. 
It does not change behavior of the npm scripts tasks but it uses `npm-run-all` instead of concurrently to run tasks in sequence or in parallel. It makes the scripts just nicer to read.
Also I made the task names more consistent by using colon in task names instead of a dash.
=> clean up npm scripts tasks with npm-run-all

package.json
We include tslint.json in the quick start files, so adding the script makes sense.
=> docs(quickstart): add lint script and dependency.

.travis.yml, package.json
This PR does a couple of things:
- adds a `test-once` npm script that runs karma in single run mode
- fixes the `e2e` script to exist automatically once protractor finishes
- runs `http-server` in the `e2e` script in silent mode, to make it easier to see test results
- runs lint, unit and e2e tests in Travis CI
/cc @wardbell @Foxandxss
=> chore(tests): add single run mode

app/app.component.spec.ts, karma-test-shim.js, karma.conf.js
**NOT** to merge until https://github.com/angular/zone.js/issues/404 is fixed.
=> chore: update specs to TestBed

protractor.config.js
Running `npm run e2e` without running `npm test` first will fail, because our protractor tests attempt to write to `./_test-output/protractor-results.txt` but `./_test-output/` does not exist yet.
Fix #196
Fix #201
=> fix(e2e): create output dir if it doesn't exist

README.md
removed advice about requiring admin access for npm install, start - this is incorrect and bad practise.
=> chore: remove "run as admin" advice from README.md

.gitignore, Dockerfile, README.md, e2e/app.e2e-spec.ts, package.json, protractor.config.js, typings.json
This PR updates the quickstart to use the `@types/*` repos. Additionally, it also updates to protractor4 to make use of it's own typings.
/cc @wardbell @Foxandxss
=> chore: update to @types

.editorconfig
Using `end_of_line` causes issues on windows machines.
=> chore(editorconfig): remove end_of_line setting

CHANGELOG.md, package.json
Coordinate with [angular.io PR #2691](https://github.com/angular/angular.io/pull/2691)
=> chore: update to 2.1.2; remove bootstrap.css

package.json
=> fix(e2e): restore e2e fix

CHANGELOG.md, package.json
Bug in Jasmine v.2.5.x, reported in https://github.com/jasmine/jasmine/issues/1231
Stick with v.2.4.1 (as karma-jasmine does) until the issue is resolved
Unfortunately, there is no @types/jasmine for v.2.4 but only for v.2.5.
=> chore(testing): revert to jasmine v.2.4.1

CHANGELOG.md, systemjs.config.js
The package is not listed in `package.json` and https://github.com/angular/angular.io/pull/2803 will contain instructions to add it manually.
=> chore(config): remove upgrade package mappings

package.json
Followup to https://github.com/angular/quickstart/pull/266, it is no longer needed.
/cc @wardbell @Foxandxss @cnishina
=> ci: update protractor

karma.conf.js
Usage of the variable currently works only because appBase and appSrcBase are defined to the same thing, but is conceptually incorrect.
=> Correction for when we change tsconfig.json/outDir and karma.conf/appBase

package.json
When https://github.com/angular/protractor/pull/3848 is ready it should fix the webdriver types issues, and the pinning can be reverted.
The zone.js problem is being tracked on https://github.com/angular/zone.js/issues/554.
Fix https://github.com/angular/quickstart/issues/325
=> fix(deps): pin webdriver and zone.js

package.json
The `@types/selenium-webdriver` is not needed since the types are a dependency of Protractor. Updating to the latest Protractor version. The new version pins the version of `@types/selenium-webdriver` to prevent issues with upstream dependencies like #325.
=> fix(deps): remove selenium-webdriver typings and update protractor version

index.html, karma.conf.js, package.json
Blocked on https://github.com/angular/in-memory-web-api/pull/86
Should be merged together with https://github.com/angular/angular.io/pull/3058
As per https://github.com/zloirock/core-js/issues/152, `core-js` already includes `reflect-metadata`.
/cc @wardbell @Foxandxss
=> chore(deps): remove reflect-metadata

README.md
Remove word 'add' from "Updating to a newer version of the Quickstart Repo" section of GitHub README.
=> docs(readme): Fix small typo in README.md

src/systemjs-angular-loader.js
"let" is ES2015 and therefore not supported by<=IE10
=> Fix systemjs-angular-loader.js for <=IE10

src/systemjs-angular-loader.js
these code changes are based on code found in the angular docs [component with external testing](https://angular.io/docs/ts/latest/guide/testing.html#!#component-with-external-template) downloadable example.
Although the refactoring I described in #444 seems pretty simple enough to understand, In my fork  you can see branches demonstrate-bug-444 & demonstrate-fix-444 for more context of this bug and how this fix it.  
I'm assuming because this code came from elsewhere in angular help/tutorial that it's okay.. but as a sidenote, the "indexof('moduleId')" seems rather poor because if you've got the word "moduleId" _anywhere_ (for example, in a line of sourcecode you just commented out) it, the module fails to load the template.  Not sure what the better solution would be, just my $0.02
=> Fix systemjs-angular-loader.js for external templates (#444)
